---
- name: Gather DRS rules for each vmware cluster and more 
  hosts: vcenter
  gather_facts: no
  collections:
    - community.vmware

  vars:
    vcenter_hostname: "vcenter.example.com"
    vcenter_username: "admin" 
    vcenter_password: "password"

  tasks:
  - name: Gather vmware clusters
    vmware_cluster_info:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
    register: cluster_info